import os
import json
from google import genai
from google.genai import types

class CloudCognitiveAuditor:
    """Connects EcoGrid AI directly to Google AI Studio for production-grade threat intelligence analytics."""
    
    def __init__(self):
        # Fetches your secure API key from system environment variables
        self.api_key = os.environ.get("GEMINI_API_KEY")
        if self.api_key:
            self.client = genai.Client(api_key=self.api_key)
        else:
            self.client = None

    def generate_executive_briefing(self, latest_transaction):
        """Streams live ledger transactions to Gemini to generate strategic infrastructure insights."""
        if not self.client:
            return "☁️ [Cloud Offline] GEMINI_API_KEY environment variable not detected. Running in localized fallback mode."
            
        prompt = f"""
        You are the Chief Enterprise Cybersecurity and Grid Systems Infrastructure Auditor for EcoGrid AI.
        Analyze this raw data block transaction generated by our autonomous multi-agent microgrid digital twin:
        
        {json.dumps(latest_transaction, indent=2)}
        
        Provide a concise, 3-sentence high-level executive summary for the municipal board directors:
        1. Summarize the operational status and any active threat vectors intercepted.
        2. Evaluate the economic or physical safety impact of the agent's action.
        3. Recommend a long-term grid fortification policy based on this specific incident.
        """
        
        try:
            response = self.client.models.generate_content(
                model='gemini-2.5-flash',
                contents=prompt,
            )
            return response.text
        except Exception as e:
            return f"⚠️ Cloud API Analysis Interrupted: {str(e)}"